# Generated by Django 5.2.1 on 2025-05-27 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approver',
        ),
        migrations.CreateModel(
            name='TaskApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_approved_status', models.CharField(blank=True, max_length=255, null=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_app.task')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_approver_set', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_approvers',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='approver',
            field=models.ManyToManyField(blank=True, related_name='client_task_approvers', through='approval_app.TaskApprover', through_fields=('Task', 'approver'), to=settings.AUTH_USER_MODEL),
        ),
    ]
