# Generated by Django 5.2.1 on 2025-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approval_needed',
            field=models.BooleanField(default=False),
        ),
    ]
