# Generated by Django 5.2.1 on 2025-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0002_client_approval_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('self-approved', 'Self Approved')], default='pending', max_length=20),
        ),
    ]
