# Generated by Django 5.2.1 on 2025-05-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0003_alter_client_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='approval_needed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_approved_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='rejection_reason',
        ),
    ]
