# Generated by Django 5.2.1 on 2025-05-26 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0004_remove_client_age_remove_client_approval_needed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.CharField(max_length=255)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete')], default='pending', max_length=50)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_due_date', models.DateField(blank=True, null=True)),
                ('task_completed_date', models.DateField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='approval_app.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_app_task',
            },
        ),
    ]
