# Generated by Django 5.2.1 on 2025-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0006_stageone_stagethree_stagetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
