# Generated by Django 5.2.1 on 2025-05-26 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0007_task_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagethree',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='stagethree',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='stagethree',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stagethree',
            name='task',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='task',
        ),
        migrations.CreateModel(
            name='ApproversCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('approvers', models.ManyToManyField(related_name='approvers_categories', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_app_approvers_category',
            },
        ),
        migrations.DeleteModel(
            name='StageOne',
        ),
        migrations.DeleteModel(
            name='StageThree',
        ),
        migrations.DeleteModel(
            name='StageTwo',
        ),
    ]
