# Generated by Django 5.2.1 on 2025-05-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0008_remove_stagethree_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers_category', to='approval_app.approverscategory'),
        ),
    ]
